enum HexCodes {
	Default = 'Default',
	White = 'White',
	Aqua = 'Aqua',
	Green = 'Green',
	Blue = 'Blue',
	Yellow = 'Yellow',
	Purple = 'Purple',
	LuminousVividPink = 'LuminousVividPink',
	Fuchsia = 'Fuchsia',
	Gold = 'Gold',
	Orange = 'Orange',
	Red = 'Red',
	Grey = 'Grey',
	Navy = 'Navy',
	DarkAqua = 'DarkAqua',
	DarkGreen = 'DarkGreen',
	DarkBlue = 'DarkBlue',
	DarkPurple = 'DarkPurple',
	DarkVividPink = 'DarkVividPink',
	DarkGold = 'DarkGold',
	DarkOrange = 'DarkOrange',
	DarkRed = 'DarkRed',
	DarkGrey = 'DarkGrey',
	DarkerGrey = 'DarkerGrey',
	LightGrey = 'LightGrey',
	DarkNavy = 'DarkNavy',
	Blurple = 'Blurple',
	Greyple = 'Greyple',
	DarkButNotBlack = 'DarkButNotBlack',
	NotQuiteBlack = 'NotQuiteBlack',
	Random = 'Random',
}

export {
	HexCodes
}